### ISSUE TITLE
Empty matchfile

### ISSUE THREAD

**Issue by huispaty** [CPJKU/asap-dataset#4]
The matchfile [MunA12M](https://github.com/CPJKU/asap-dataset/blob/main/Debussy/Pour_le_Piano/1/MunA12M.match) for the first movement of Pour le Piano by Debussy is empty.

**Comment by sildater** [comment]
hey @manoskary do you know what could have happened there?

**Comment by manoskary** [comment]
I think there might be two possibilities:
- The piece was not rendered complete due to a SIGKill or some kind of try-except clause.
- The piece was not rendered complete due to an unfolding error.

I corrected the piece and I'm ready to push the changes. Do you think that we should do a release update?

**Comment by sildater** [comment]
you can create a new branch for the next release for this. Thank you!
